/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AfrekenenRouteImport } from './routes/afrekenen'
import { Route as BeheerRouteImport } from './routes/beheer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InloggenRouteImport } from './routes/inloggen'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RetourenRouteImport } from './routes/retouren'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VeelgesteldeVragenRouteImport } from './routes/veelgestelde-vragen'
import { Route as VerlanglijstRouteImport } from './routes/verlanglijst'
import { Route as VerzendingRouteImport } from './routes/verzending'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as WinkelRouteImport } from './routes/winkel'
import { Route as WinkelwagenRouteImport } from './routes/winkelwagen'
import { Route as BeheerIndexRouteImport } from './routes/beheer.index'
import { Route as BeheerAuditRouteImport } from './routes/beheer.audit'
import { Route as BeheerBeoordelingenRouteImport } from './routes/beheer.beoordelingen'
import { Route as BeheerBerichtenRouteImport } from './routes/beheer.berichten'
import { Route as BeheerBestellingenRouteImport } from './routes/beheer.bestellingen'
import { Route as BeheerBolcomRouteImport } from './routes/beheer.bolcom'
import { Route as BeheerCategorieenRouteImport } from './routes/beheer.categorieen'
import { Route as BeheerGebruikersRouteImport } from './routes/beheer.gebruikers'
import { Route as BeheerImportRouteImport } from './routes/beheer.import'
import { Route as BeheerKlantenRouteImport } from './routes/beheer.klanten'
import { Route as BeheerLageVoorraadRouteImport } from './routes/beheer.lage-voorraad'
import { Route as BeheerMerkenRouteImport } from './routes/beheer.merken'
import { Route as BeheerMutatiesRouteImport } from './routes/beheer.mutaties'
import { Route as BeheerProductenRouteImport } from './routes/beheer.producten'
import { Route as BeheerRapportenRouteImport } from './routes/beheer.rapporten'
import { Route as BeheerRetourenRouteImport } from './routes/beheer.retouren'
import { Route as BeheerVertalingenRouteImport } from './routes/beheer.vertalingen'
import { Route as BeheerVoorraadRouteImport } from './routes/beheer.voorraad'
import { Route as BestellingOrderNumberRouteImport } from './routes/bestelling.$orderNumber'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicBolSyncRouteImport } from './routes/api/public/bol-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AfrekenenRoute = AfrekenenRouteImport.update({
  id: '/afrekenen',
  path: '/afrekenen',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerRoute = BeheerRouteImport.update({
  id: '/beheer',
  path: '/beheer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InloggenRoute = InloggenRouteImport.update({
  id: '/inloggen',
  path: '/inloggen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RetourenRoute = RetourenRouteImport.update({
  id: '/retouren',
  path: '/retouren',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VeelgesteldeVragenRoute = VeelgesteldeVragenRouteImport.update({
  id: '/veelgestelde-vragen',
  path: '/veelgestelde-vragen',
  getParentRoute: () => rootRouteImport,
} as any)
const VerlanglijstRoute = VerlanglijstRouteImport.update({
  id: '/verlanglijst',
  path: '/verlanglijst',
  getParentRoute: () => rootRouteImport,
} as any)
const VerzendingRoute = VerzendingRouteImport.update({
  id: '/verzending',
  path: '/verzending',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelRoute = WinkelRouteImport.update({
  id: '/winkel',
  path: '/winkel',
  getParentRoute: () => rootRouteImport,
} as any)
const WinkelwagenRoute = WinkelwagenRouteImport.update({
  id: '/winkelwagen',
  path: '/winkelwagen',
  getParentRoute: () => rootRouteImport,
} as any)
const BeheerIndexRoute = BeheerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerAuditRoute = BeheerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerBeoordelingenRoute = BeheerBeoordelingenRouteImport.update({
  id: '/beoordelingen',
  path: '/beoordelingen',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerBerichtenRoute = BeheerBerichtenRouteImport.update({
  id: '/berichten',
  path: '/berichten',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerBestellingenRoute = BeheerBestellingenRouteImport.update({
  id: '/bestellingen',
  path: '/bestellingen',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerBolcomRoute = BeheerBolcomRouteImport.update({
  id: '/bolcom',
  path: '/bolcom',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerCategorieenRoute = BeheerCategorieenRouteImport.update({
  id: '/categorieen',
  path: '/categorieen',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerGebruikersRoute = BeheerGebruikersRouteImport.update({
  id: '/gebruikers',
  path: '/gebruikers',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerImportRoute = BeheerImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerKlantenRoute = BeheerKlantenRouteImport.update({
  id: '/klanten',
  path: '/klanten',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerLageVoorraadRoute = BeheerLageVoorraadRouteImport.update({
  id: '/lage-voorraad',
  path: '/lage-voorraad',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerMerkenRoute = BeheerMerkenRouteImport.update({
  id: '/merken',
  path: '/merken',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerMutatiesRoute = BeheerMutatiesRouteImport.update({
  id: '/mutaties',
  path: '/mutaties',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerProductenRoute = BeheerProductenRouteImport.update({
  id: '/producten',
  path: '/producten',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerRapportenRoute = BeheerRapportenRouteImport.update({
  id: '/rapporten',
  path: '/rapporten',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerRetourenRoute = BeheerRetourenRouteImport.update({
  id: '/retouren',
  path: '/retouren',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerVertalingenRoute = BeheerVertalingenRouteImport.update({
  id: '/vertalingen',
  path: '/vertalingen',
  getParentRoute: () => BeheerRoute,
} as any)
const BeheerVoorraadRoute = BeheerVoorraadRouteImport.update({
  id: '/voorraad',
  path: '/voorraad',
  getParentRoute: () => BeheerRoute,
} as any)
const BestellingOrderNumberRoute = BestellingOrderNumberRouteImport.update({
  id: '/bestelling/$orderNumber',
  path: '/bestelling/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBolSyncRoute = ApiPublicBolSyncRouteImport.update({
  id: '/api/public/bol-sync',
  path: '/api/public/bol-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/afrekenen': typeof AfrekenenRoute
  '/beheer': typeof BeheerRouteWithChildren
  '/contact': typeof ContactRoute
  '/inloggen': typeof InloggenRoute
  '/privacy': typeof PrivacyRoute
  '/retouren': typeof RetourenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/verlanglijst': typeof VerlanglijstRoute
  '/verzending': typeof VerzendingRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/winkel': typeof WinkelRoute
  '/winkelwagen': typeof WinkelwagenRoute
  '/beheer/audit': typeof BeheerAuditRoute
  '/beheer/beoordelingen': typeof BeheerBeoordelingenRoute
  '/beheer/berichten': typeof BeheerBerichtenRoute
  '/beheer/bestellingen': typeof BeheerBestellingenRoute
  '/beheer/bolcom': typeof BeheerBolcomRoute
  '/beheer/categorieen': typeof BeheerCategorieenRoute
  '/beheer/gebruikers': typeof BeheerGebruikersRoute
  '/beheer/import': typeof BeheerImportRoute
  '/beheer/klanten': typeof BeheerKlantenRoute
  '/beheer/lage-voorraad': typeof BeheerLageVoorraadRoute
  '/beheer/merken': typeof BeheerMerkenRoute
  '/beheer/mutaties': typeof BeheerMutatiesRoute
  '/beheer/producten': typeof BeheerProductenRoute
  '/beheer/rapporten': typeof BeheerRapportenRoute
  '/beheer/retouren': typeof BeheerRetourenRoute
  '/beheer/vertalingen': typeof BeheerVertalingenRoute
  '/beheer/voorraad': typeof BeheerVoorraadRoute
  '/bestelling/$orderNumber': typeof BestellingOrderNumberRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/beheer/': typeof BeheerIndexRoute
  '/api/public/bol-sync': typeof ApiPublicBolSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/afrekenen': typeof AfrekenenRoute
  '/contact': typeof ContactRoute
  '/inloggen': typeof InloggenRoute
  '/privacy': typeof PrivacyRoute
  '/retouren': typeof RetourenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/verlanglijst': typeof VerlanglijstRoute
  '/verzending': typeof VerzendingRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/winkel': typeof WinkelRoute
  '/winkelwagen': typeof WinkelwagenRoute
  '/beheer/audit': typeof BeheerAuditRoute
  '/beheer/beoordelingen': typeof BeheerBeoordelingenRoute
  '/beheer/berichten': typeof BeheerBerichtenRoute
  '/beheer/bestellingen': typeof BeheerBestellingenRoute
  '/beheer/bolcom': typeof BeheerBolcomRoute
  '/beheer/categorieen': typeof BeheerCategorieenRoute
  '/beheer/gebruikers': typeof BeheerGebruikersRoute
  '/beheer/import': typeof BeheerImportRoute
  '/beheer/klanten': typeof BeheerKlantenRoute
  '/beheer/lage-voorraad': typeof BeheerLageVoorraadRoute
  '/beheer/merken': typeof BeheerMerkenRoute
  '/beheer/mutaties': typeof BeheerMutatiesRoute
  '/beheer/producten': typeof BeheerProductenRoute
  '/beheer/rapporten': typeof BeheerRapportenRoute
  '/beheer/retouren': typeof BeheerRetourenRoute
  '/beheer/vertalingen': typeof BeheerVertalingenRoute
  '/beheer/voorraad': typeof BeheerVoorraadRoute
  '/bestelling/$orderNumber': typeof BestellingOrderNumberRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/beheer': typeof BeheerIndexRoute
  '/api/public/bol-sync': typeof ApiPublicBolSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/afrekenen': typeof AfrekenenRoute
  '/beheer': typeof BeheerRouteWithChildren
  '/contact': typeof ContactRoute
  '/inloggen': typeof InloggenRoute
  '/privacy': typeof PrivacyRoute
  '/retouren': typeof RetourenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/verlanglijst': typeof VerlanglijstRoute
  '/verzending': typeof VerzendingRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/winkel': typeof WinkelRoute
  '/winkelwagen': typeof WinkelwagenRoute
  '/beheer/audit': typeof BeheerAuditRoute
  '/beheer/beoordelingen': typeof BeheerBeoordelingenRoute
  '/beheer/berichten': typeof BeheerBerichtenRoute
  '/beheer/bestellingen': typeof BeheerBestellingenRoute
  '/beheer/bolcom': typeof BeheerBolcomRoute
  '/beheer/categorieen': typeof BeheerCategorieenRoute
  '/beheer/gebruikers': typeof BeheerGebruikersRoute
  '/beheer/import': typeof BeheerImportRoute
  '/beheer/klanten': typeof BeheerKlantenRoute
  '/beheer/lage-voorraad': typeof BeheerLageVoorraadRoute
  '/beheer/merken': typeof BeheerMerkenRoute
  '/beheer/mutaties': typeof BeheerMutatiesRoute
  '/beheer/producten': typeof BeheerProductenRoute
  '/beheer/rapporten': typeof BeheerRapportenRoute
  '/beheer/retouren': typeof BeheerRetourenRoute
  '/beheer/vertalingen': typeof BeheerVertalingenRoute
  '/beheer/voorraad': typeof BeheerVoorraadRoute
  '/bestelling/$orderNumber': typeof BestellingOrderNumberRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/beheer/': typeof BeheerIndexRoute
  '/api/public/bol-sync': typeof ApiPublicBolSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/afrekenen'
    | '/beheer'
    | '/contact'
    | '/inloggen'
    | '/privacy'
    | '/retouren'
    | '/sitemap.xml'
    | '/veelgestelde-vragen'
    | '/verlanglijst'
    | '/verzending'
    | '/voorwaarden'
    | '/winkel'
    | '/winkelwagen'
    | '/beheer/audit'
    | '/beheer/beoordelingen'
    | '/beheer/berichten'
    | '/beheer/bestellingen'
    | '/beheer/bolcom'
    | '/beheer/categorieen'
    | '/beheer/gebruikers'
    | '/beheer/import'
    | '/beheer/klanten'
    | '/beheer/lage-voorraad'
    | '/beheer/merken'
    | '/beheer/mutaties'
    | '/beheer/producten'
    | '/beheer/rapporten'
    | '/beheer/retouren'
    | '/beheer/vertalingen'
    | '/beheer/voorraad'
    | '/bestelling/$orderNumber'
    | '/categorie/$slug'
    | '/product/$slug'
    | '/beheer/'
    | '/api/public/bol-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/afrekenen'
    | '/contact'
    | '/inloggen'
    | '/privacy'
    | '/retouren'
    | '/sitemap.xml'
    | '/veelgestelde-vragen'
    | '/verlanglijst'
    | '/verzending'
    | '/voorwaarden'
    | '/winkel'
    | '/winkelwagen'
    | '/beheer/audit'
    | '/beheer/beoordelingen'
    | '/beheer/berichten'
    | '/beheer/bestellingen'
    | '/beheer/bolcom'
    | '/beheer/categorieen'
    | '/beheer/gebruikers'
    | '/beheer/import'
    | '/beheer/klanten'
    | '/beheer/lage-voorraad'
    | '/beheer/merken'
    | '/beheer/mutaties'
    | '/beheer/producten'
    | '/beheer/rapporten'
    | '/beheer/retouren'
    | '/beheer/vertalingen'
    | '/beheer/voorraad'
    | '/bestelling/$orderNumber'
    | '/categorie/$slug'
    | '/product/$slug'
    | '/beheer'
    | '/api/public/bol-sync'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/afrekenen'
    | '/beheer'
    | '/contact'
    | '/inloggen'
    | '/privacy'
    | '/retouren'
    | '/sitemap.xml'
    | '/veelgestelde-vragen'
    | '/verlanglijst'
    | '/verzending'
    | '/voorwaarden'
    | '/winkel'
    | '/winkelwagen'
    | '/beheer/audit'
    | '/beheer/beoordelingen'
    | '/beheer/berichten'
    | '/beheer/bestellingen'
    | '/beheer/bolcom'
    | '/beheer/categorieen'
    | '/beheer/gebruikers'
    | '/beheer/import'
    | '/beheer/klanten'
    | '/beheer/lage-voorraad'
    | '/beheer/merken'
    | '/beheer/mutaties'
    | '/beheer/producten'
    | '/beheer/rapporten'
    | '/beheer/retouren'
    | '/beheer/vertalingen'
    | '/beheer/voorraad'
    | '/bestelling/$orderNumber'
    | '/categorie/$slug'
    | '/product/$slug'
    | '/beheer/'
    | '/api/public/bol-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AfrekenenRoute: typeof AfrekenenRoute
  BeheerRoute: typeof BeheerRouteWithChildren
  ContactRoute: typeof ContactRoute
  InloggenRoute: typeof InloggenRoute
  PrivacyRoute: typeof PrivacyRoute
  RetourenRoute: typeof RetourenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VeelgesteldeVragenRoute: typeof VeelgesteldeVragenRoute
  VerlanglijstRoute: typeof VerlanglijstRoute
  VerzendingRoute: typeof VerzendingRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  WinkelRoute: typeof WinkelRoute
  WinkelwagenRoute: typeof WinkelwagenRoute
  BestellingOrderNumberRoute: typeof BestellingOrderNumberRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicBolSyncRoute: typeof ApiPublicBolSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afrekenen': {
      id: '/afrekenen'
      path: '/afrekenen'
      fullPath: '/afrekenen'
      preLoaderRoute: typeof AfrekenenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer': {
      id: '/beheer'
      path: '/beheer'
      fullPath: '/beheer'
      preLoaderRoute: typeof BeheerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inloggen': {
      id: '/inloggen'
      path: '/inloggen'
      fullPath: '/inloggen'
      preLoaderRoute: typeof InloggenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retouren': {
      id: '/retouren'
      path: '/retouren'
      fullPath: '/retouren'
      preLoaderRoute: typeof RetourenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veelgestelde-vragen': {
      id: '/veelgestelde-vragen'
      path: '/veelgestelde-vragen'
      fullPath: '/veelgestelde-vragen'
      preLoaderRoute: typeof VeelgesteldeVragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verlanglijst': {
      id: '/verlanglijst'
      path: '/verlanglijst'
      fullPath: '/verlanglijst'
      preLoaderRoute: typeof VerlanglijstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verzending': {
      id: '/verzending'
      path: '/verzending'
      fullPath: '/verzending'
      preLoaderRoute: typeof VerzendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkel': {
      id: '/winkel'
      path: '/winkel'
      fullPath: '/winkel'
      preLoaderRoute: typeof WinkelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winkelwagen': {
      id: '/winkelwagen'
      path: '/winkelwagen'
      fullPath: '/winkelwagen'
      preLoaderRoute: typeof WinkelwagenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beheer/': {
      id: '/beheer/'
      path: '/'
      fullPath: '/beheer/'
      preLoaderRoute: typeof BeheerIndexRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/audit': {
      id: '/beheer/audit'
      path: '/audit'
      fullPath: '/beheer/audit'
      preLoaderRoute: typeof BeheerAuditRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/beoordelingen': {
      id: '/beheer/beoordelingen'
      path: '/beoordelingen'
      fullPath: '/beheer/beoordelingen'
      preLoaderRoute: typeof BeheerBeoordelingenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/berichten': {
      id: '/beheer/berichten'
      path: '/berichten'
      fullPath: '/beheer/berichten'
      preLoaderRoute: typeof BeheerBerichtenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/bestellingen': {
      id: '/beheer/bestellingen'
      path: '/bestellingen'
      fullPath: '/beheer/bestellingen'
      preLoaderRoute: typeof BeheerBestellingenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/bolcom': {
      id: '/beheer/bolcom'
      path: '/bolcom'
      fullPath: '/beheer/bolcom'
      preLoaderRoute: typeof BeheerBolcomRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/categorieen': {
      id: '/beheer/categorieen'
      path: '/categorieen'
      fullPath: '/beheer/categorieen'
      preLoaderRoute: typeof BeheerCategorieenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/gebruikers': {
      id: '/beheer/gebruikers'
      path: '/gebruikers'
      fullPath: '/beheer/gebruikers'
      preLoaderRoute: typeof BeheerGebruikersRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/import': {
      id: '/beheer/import'
      path: '/import'
      fullPath: '/beheer/import'
      preLoaderRoute: typeof BeheerImportRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/klanten': {
      id: '/beheer/klanten'
      path: '/klanten'
      fullPath: '/beheer/klanten'
      preLoaderRoute: typeof BeheerKlantenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/lage-voorraad': {
      id: '/beheer/lage-voorraad'
      path: '/lage-voorraad'
      fullPath: '/beheer/lage-voorraad'
      preLoaderRoute: typeof BeheerLageVoorraadRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/merken': {
      id: '/beheer/merken'
      path: '/merken'
      fullPath: '/beheer/merken'
      preLoaderRoute: typeof BeheerMerkenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/mutaties': {
      id: '/beheer/mutaties'
      path: '/mutaties'
      fullPath: '/beheer/mutaties'
      preLoaderRoute: typeof BeheerMutatiesRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/producten': {
      id: '/beheer/producten'
      path: '/producten'
      fullPath: '/beheer/producten'
      preLoaderRoute: typeof BeheerProductenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/rapporten': {
      id: '/beheer/rapporten'
      path: '/rapporten'
      fullPath: '/beheer/rapporten'
      preLoaderRoute: typeof BeheerRapportenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/retouren': {
      id: '/beheer/retouren'
      path: '/retouren'
      fullPath: '/beheer/retouren'
      preLoaderRoute: typeof BeheerRetourenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/vertalingen': {
      id: '/beheer/vertalingen'
      path: '/vertalingen'
      fullPath: '/beheer/vertalingen'
      preLoaderRoute: typeof BeheerVertalingenRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/beheer/voorraad': {
      id: '/beheer/voorraad'
      path: '/voorraad'
      fullPath: '/beheer/voorraad'
      preLoaderRoute: typeof BeheerVoorraadRouteImport
      parentRoute: typeof BeheerRoute
    }
    '/bestelling/$orderNumber': {
      id: '/bestelling/$orderNumber'
      path: '/bestelling/$orderNumber'
      fullPath: '/bestelling/$orderNumber'
      preLoaderRoute: typeof BestellingOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bol-sync': {
      id: '/api/public/bol-sync'
      path: '/api/public/bol-sync'
      fullPath: '/api/public/bol-sync'
      preLoaderRoute: typeof ApiPublicBolSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BeheerRouteChildren {
  BeheerAuditRoute: typeof BeheerAuditRoute
  BeheerBeoordelingenRoute: typeof BeheerBeoordelingenRoute
  BeheerBerichtenRoute: typeof BeheerBerichtenRoute
  BeheerBestellingenRoute: typeof BeheerBestellingenRoute
  BeheerBolcomRoute: typeof BeheerBolcomRoute
  BeheerCategorieenRoute: typeof BeheerCategorieenRoute
  BeheerGebruikersRoute: typeof BeheerGebruikersRoute
  BeheerImportRoute: typeof BeheerImportRoute
  BeheerKlantenRoute: typeof BeheerKlantenRoute
  BeheerLageVoorraadRoute: typeof BeheerLageVoorraadRoute
  BeheerMerkenRoute: typeof BeheerMerkenRoute
  BeheerMutatiesRoute: typeof BeheerMutatiesRoute
  BeheerProductenRoute: typeof BeheerProductenRoute
  BeheerRapportenRoute: typeof BeheerRapportenRoute
  BeheerRetourenRoute: typeof BeheerRetourenRoute
  BeheerVertalingenRoute: typeof BeheerVertalingenRoute
  BeheerVoorraadRoute: typeof BeheerVoorraadRoute
  BeheerIndexRoute: typeof BeheerIndexRoute
}

const BeheerRouteChildren: BeheerRouteChildren = {
  BeheerAuditRoute: BeheerAuditRoute,
  BeheerBeoordelingenRoute: BeheerBeoordelingenRoute,
  BeheerBerichtenRoute: BeheerBerichtenRoute,
  BeheerBestellingenRoute: BeheerBestellingenRoute,
  BeheerBolcomRoute: BeheerBolcomRoute,
  BeheerCategorieenRoute: BeheerCategorieenRoute,
  BeheerGebruikersRoute: BeheerGebruikersRoute,
  BeheerImportRoute: BeheerImportRoute,
  BeheerKlantenRoute: BeheerKlantenRoute,
  BeheerLageVoorraadRoute: BeheerLageVoorraadRoute,
  BeheerMerkenRoute: BeheerMerkenRoute,
  BeheerMutatiesRoute: BeheerMutatiesRoute,
  BeheerProductenRoute: BeheerProductenRoute,
  BeheerRapportenRoute: BeheerRapportenRoute,
  BeheerRetourenRoute: BeheerRetourenRoute,
  BeheerVertalingenRoute: BeheerVertalingenRoute,
  BeheerVoorraadRoute: BeheerVoorraadRoute,
  BeheerIndexRoute: BeheerIndexRoute,
}

const BeheerRouteWithChildren =
  BeheerRoute._addFileChildren(BeheerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AfrekenenRoute: AfrekenenRoute,
  BeheerRoute: BeheerRouteWithChildren,
  ContactRoute: ContactRoute,
  InloggenRoute: InloggenRoute,
  PrivacyRoute: PrivacyRoute,
  RetourenRoute: RetourenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VeelgesteldeVragenRoute: VeelgesteldeVragenRoute,
  VerlanglijstRoute: VerlanglijstRoute,
  VerzendingRoute: VerzendingRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  WinkelRoute: WinkelRoute,
  WinkelwagenRoute: WinkelwagenRoute,
  BestellingOrderNumberRoute: BestellingOrderNumberRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicBolSyncRoute: ApiPublicBolSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
