WITH t(id, en, de, fr) AS (
VALUES
('3006bf60-fe09-4305-90c5-9a1453460cef'::uuid,
 'Replace a leaking or limescale-clogged hose in no time with this stainless steel shower hose. The double anti-kink protection prevents twisting and the brass fittings create a watertight seal on virtually any shower head or tap.',
 'Ersetzen Sie einen undichten oder verkalkten Schlauch mühelos durch diesen Duschschlauch aus Edelstahl. Der doppelte Knickschutz verhindert Verdrehen und die Messingverschraubungen dichten an nahezu jedem Duschkopf und jeder Armatur wasserdicht ab.',
 'Remplacez facilement un flexible qui fuit ou entartré par ce flexible de douche en acier inoxydable. La double protection anti-torsion évite les nœuds et les écrous en laiton assurent une étanchéité parfaite sur presque tous les pommeaux et robinets.'),
('4a318831-db7b-4d9d-9d8d-895fc0d73bb2',
 'Install a reliable doorbell in minutes without any wiring. The push button is weather resistant and works up to 300 metres from the receiver. Choose from 58 melodies and five volume levels, including a silent flash mode.',
 'Installieren Sie in wenigen Minuten eine zuverlässige Türklingel ohne Verkabelung. Der Druckknopf ist wetterfest und funktioniert bis zu 300 Meter vom Empfänger entfernt. Wählen Sie aus 58 Melodien und fünf Lautstärkestufen, inklusive lautlosem Blitzmodus.',
 'Installez en quelques minutes une sonnette fiable sans aucun câblage. Le bouton-poussoir résiste aux intempéries et fonctionne jusqu''à 300 mètres du récepteur. Choisissez parmi 58 mélodies et cinq niveaux de volume, dont un mode flash silencieux.'),
('64fe6991-4aff-4c7d-9820-e9029ad3f113',
 'This shower head combines ten spray modes with a built-in mineral filter that reduces chlorine and limescale. The result is softer water, more comfortable skin and less scale build-up. The water-saving technology increases pressure while lowering consumption.',
 'Dieser Duschkopf kombiniert zehn Strahlarten mit einem integrierten Mineralfilter, der Chlor und Kalk reduziert. Das Ergebnis ist weicheres Wasser, angenehmere Haut und weniger Kalkablagerungen. Die wassersparende Technologie erhöht den Druck und senkt den Verbrauch.',
 'Ce pommeau de douche combine dix types de jet avec un filtre minéral intégré qui réduit le chlore et le calcaire. Résultat : une eau plus douce, une peau plus agréable et moins de dépôts. La technologie d''économie d''eau augmente la pression tout en réduisant la consommation.'),
('acb76129-7801-40f4-8c45-5ab62168964f',
 'Give plants enough light all year round with this full-spectrum grow lamp. Aim the flexible arms exactly where needed, and the automatic 4, 8 or 12 hour timer keeps a steady daily rhythm.',
 'Versorgen Sie Pflanzen das ganze Jahr über mit ausreichend Licht – mit dieser Vollspektrum-Pflanzenlampe. Die flexiblen Arme richten Sie genau dorthin, wo sie gebraucht werden, und der automatische Timer mit 4, 8 oder 12 Stunden sorgt für einen festen Tagesrhythmus.',
 'Offrez à vos plantes une lumière suffisante toute l''année avec cette lampe de croissance à spectre complet. Orientez les bras flexibles exactement où il faut ; la minuterie automatique de 4, 8 ou 12 heures assure un rythme quotidien régulier.'),
('8d3339d9-cc5b-462b-868b-8a900adae609',
 'Hands-free lighting for DIY jobs, running and camping. The head torch switches on and off with a wave of your hand thanks to the built-in sensor. The light head tilts 60 degrees and the band is fully adjustable and washable.',
 'Handfreies Licht für Heimwerken, Laufen und Camping. Die Stirnlampe schaltet sich dank des integrierten Sensors mit einer Handbewegung ein und aus. Der Leuchtkopf ist um 60 Grad neigbar, das Band ist voll verstellbar und waschbar.',
 'Un éclairage mains libres pour le bricolage, la course et le camping. La lampe frontale s''allume et s''éteint d''un simple geste grâce au capteur intégré. La tête d''éclairage s''incline à 60 degrés et le bandeau est entièrement réglable et lavable.'),
('93c367b3-684d-453c-b7aa-db5d6a3aff2a',
 'The Besjaar Rechargeable Torch delivers up to 5000 lumens and effortlessly lights up your garden, shed or walking path. Made of anodised aluminium, splash-proof to IPX6 and charged via USB-C. With five modes including an SOS function, it suits both daily use and emergencies.',
 'Die Besjaar Akku-Taschenlampe liefert bis zu 5000 Lumen und beleuchtet Garten, Schuppen oder Wanderweg mühelos. Sie besteht aus anodisiertem Aluminium, ist nach IPX6 spritzwassergeschützt und wird über USB-C geladen. Mit fünf Modi, darunter eine SOS-Funktion, eignet sie sich für den Alltag und für Notfälle.',
 'La lampe torche rechargeable Besjaar délivre jusqu''à 5000 lumens et éclaire sans effort jardin, remise ou sentier. En aluminium anodisé, résistante aux projections d''eau selon IPX6 et rechargeable en USB-C. Avec cinq modes dont une fonction SOS, elle convient à un usage quotidien comme aux situations d''urgence.'),
('9bb7ca17-5273-44e7-a944-5ea913631569',
 'Charge your phone up to four times over with this 20000 mAh power bank. Thanks to 22.5 W fast charging and three outputs you can charge several devices at once. The display shows the exact remaining capacity as a percentage.',
 'Laden Sie Ihr Smartphone mit dieser 20000-mAh-Powerbank bis zu viermal vollständig auf. Dank 22,5 W Schnellladung und drei Ausgängen laden Sie mehrere Geräte gleichzeitig. Das Display zeigt die Restkapazität exakt in Prozent an.',
 'Rechargez votre téléphone jusqu''à quatre fois avec cette batterie externe de 20000 mAh. Grâce à la charge rapide 22,5 W et à trois sorties, vous chargez plusieurs appareils en même temps. L''écran affiche la capacité restante en pourcentage exact.'),
('0f8e8ec7-b608-4aca-8fe4-3808c192dc07',
 'This solar lamp charges during the day and lights up your driveway, garden path or back door at night as soon as motion is detected. With 120 LEDs, an 8 metre detection range and IP65 protection it can be used all year round.',
 'Diese Solarleuchte lädt sich tagsüber auf und beleuchtet nachts Einfahrt, Gartenweg oder Hintertür, sobald Bewegung erkannt wird. Mit 120 LEDs, 8 Metern Erfassungsbereich und IP65-Schutz ist sie das ganze Jahr über einsetzbar.',
 'Cette lampe solaire se recharge le jour et éclaire la nuit l''allée, le chemin de jardin ou la porte arrière dès qu''un mouvement est détecté. Avec 120 LED, une portée de détection de 8 mètres et une protection IP65, elle s''utilise toute l''année.'),
('bc16e642-22d1-42f5-8026-45b36cb1ecd5',
 'With 51 UV LEDs this torch instantly reveals invisible stains, pet urine, leaks in air conditioning systems and counterfeits. Compact format with wrist strap, powered by AA batteries.',
 'Mit 51 UV-LEDs macht diese Taschenlampe unsichtbare Flecken, Haustierurin, Leckagen in Klimaanlagen und Fälschungen sofort sichtbar. Kompaktes Format mit Handschlaufe, Betrieb mit AA-Batterien.',
 'Avec 51 LED UV, cette lampe révèle instantanément les taches invisibles, l''urine d''animaux, les fuites des systèmes de climatisation et les contrefaçons. Format compact avec dragonne, fonctionne avec des piles AA.'),
('5bb6dc48-59c0-481b-a843-0439027326fe',
 'This torch is the most powerful model in the Besjaar range. With 7400 lumens and a beam up to 500 metres it is ideal for outdoor work, hunting and security. The lamp also has a power bank function so you can top up your phone on the go.',
 'Diese Taschenlampe ist das leistungsstärkste Modell der Besjaar-Serie. Mit 7400 Lumen und einer Leuchtweite von bis zu 500 Metern ist sie ideal für Arbeiten im Freien, Jagd und Sicherheitsdienste. Die Lampe verfügt über eine Powerbank-Funktion, sodass Sie unterwegs Ihr Handy laden können.',
 'Cette lampe torche est le modèle le plus puissant de la gamme Besjaar. Avec 7400 lumens et un faisceau jusqu''à 500 mètres, elle est idéale pour les travaux en extérieur, la chasse et la sécurité. Elle intègre une fonction batterie externe pour recharger votre téléphone en déplacement.'),
('afbda2c4-a633-40ba-a52c-a034de868cbb',
 'Style your hair with warm air instead of extreme heat. The LYNEX 5-in-1 Airstyler combines drying, curling, brushing and volumising in one device, with ion technology against frizz and three temperature settings.',
 'Stylen Sie Ihr Haar mit warmer Luft statt extremer Hitze. Der LYNEX 5-in-1 Airstyler vereint Föhnen, Locken, Bürsten und Volumen in einem Gerät – mit Ionen-Technologie gegen Frizz und drei Temperaturstufen.',
 'Coiffez vos cheveux à l''air chaud plutôt qu''à une chaleur extrême. L''Airstyler LYNEX 5-en-1 combine séchage, boucles, brossage et volume en un seul appareil, avec technologie ionique anti-frisottis et trois niveaux de température.'),
('3b9b0443-5a77-4873-adba-96e2e55279ad',
 'The extended model with seven attachments, including two curling barrels, a diffuser and two brushes. Ideal for long and thick hair thanks to the powerful airflow and the automatic heat protection.',
 'Das erweiterte Modell mit sieben Aufsätzen, darunter zwei Lockenstäbe, ein Diffusor und zwei Bürsten. Ideal für langes und dickes Haar dank des kräftigen Luftstroms und des automatischen Hitzeschutzes.',
 'Le modèle complet avec sept accessoires, dont deux fers à boucler, un diffuseur et deux brosses. Idéal pour les cheveux longs et épais grâce au flux d''air puissant et à la protection thermique automatique.'),
('7c9ad90f-cdad-40fe-afcb-ed7d14150a19',
 'This thermal brush heats evenly and smooths your hair while you brush. The ceramic coating spreads the heat without hot spots and the device is ready to use within 30 seconds.',
 'Diese Thermobürste erwärmt sich gleichmäßig und glättet Ihr Haar beim Bürsten. Die Keramikbeschichtung verteilt die Wärme ohne heiße Stellen und das Gerät ist in 30 Sekunden einsatzbereit.',
 'Cette brosse chauffante chauffe uniformément et lisse vos cheveux pendant le brossage. Le revêtement céramique répartit la chaleur sans points chauds et l''appareil est prêt en 30 secondes.'),
('b4814262-433c-45b4-acdd-099c3dde1a2b',
 'Professional alcohol markers with a fine and a broad tip. The ink dries quickly, blends well and flows evenly without streaks. Includes a handy storage case.',
 'Professionelle Alkoholmarker mit feiner und breiter Spitze. Die Tinte trocknet schnell, lässt sich mischen und fließt gleichmäßig ohne Streifen. Inklusive praktischer Aufbewahrungsbox.',
 'Marqueurs à alcool professionnels avec une pointe fine et une pointe large. L''encre sèche vite, se mélange facilement et s''écoule uniformément sans traces. Étui de rangement pratique inclus.'),
('cec2058c-7951-4bf6-9651-4a93bac71842',
 'Ideal for larger quantities: dough, meat or parcels up to 10 kilos. The wide weighing platform fits big bowls and the clear LCD stays readable even underneath a bowl.',
 'Ideal für größere Mengen: Teig, Fleisch oder Pakete bis 10 Kilo. Die breite Wiegefläche bietet Platz für große Schüsseln und das gut lesbare LCD bleibt auch unter einer Schüssel ablesbar.',
 'Idéale pour les grandes quantités : pâte, viande ou colis jusqu''à 10 kilos. Le large plateau accueille de grands récipients et l''écran LCD reste lisible même sous un saladier.'),
('8e3f7800-7eaf-4206-ae49-b07009c6be1b',
 'Weigh ingredients accurate to the gram. The tempered glass surface is easy to clean and the tare function automatically subtracts the weight of your bowl. Switches off automatically to save batteries.',
 'Wiegen Sie Zutaten grammgenau. Die Oberfläche aus gehärtetem Glas ist leicht zu reinigen und die Tara-Funktion zieht das Gewicht Ihrer Schüssel automatisch ab. Schaltet sich automatisch ab, um Batterien zu sparen.',
 'Pesez vos ingrédients au gramme près. La surface en verre trempé se nettoie facilement et la fonction tare soustrait automatiquement le poids de votre récipient. Extinction automatique pour économiser les piles.'),
('ba673fc5-516c-477a-9ae9-0a6fe16e4f67',
 'This phone holder clamps firmly onto an air vent or desk and keeps your phone stable at the height you want. The 360 degree rotation allows both portrait and landscape use.',
 'Diese Handyhalterung klemmt sicher am Lüftungsgitter oder Schreibtisch und hält Ihr Telefon stabil auf der gewünschten Höhe. Die 360-Grad-Drehung ermöglicht Hoch- und Querformat.',
 'Ce support de téléphone se fixe fermement sur une grille d''aération ou un bureau et maintient votre téléphone stable à la hauteur souhaitée. La rotation à 360 degrés permet un usage en portrait comme en paysage.'),
('66df14e4-a1cb-42ec-8ce2-5312890171c3',
 'One adapter for all your travels. The RYNEX travel adapter combines plugs for the EU, US, UK and Australia with four USB ports including USB-C Power Delivery. The built-in fuse and safety cover protect your devices.',
 'Ein Adapter für alle Reisen. Der RYNEX Reiseadapter vereint Stecker für EU, USA, UK und Australien mit vier USB-Anschlüssen, darunter USB-C Power Delivery. Die integrierte Sicherung und die Sicherheitsabdeckung schützen Ihre Geräte.',
 'Un seul adaptateur pour tous vos voyages. L''adaptateur de voyage RYNEX réunit les prises UE, US, UK et Australie avec quatre ports USB dont un USB-C Power Delivery. Le fusible intégré et le cache de sécurité protègent vos appareils.'),
('90b970ba-7628-4217-ba96-26572935521d',
 'Read SD and microSD cards directly on your laptop, tablet or phone. The aluminium housing dissipates heat and the dual connector makes the reader compatible with virtually any device.',
 'Lesen Sie SD- und microSD-Karten direkt auf Laptop, Tablet oder Smartphone. Das Aluminiumgehäuse leitet Wärme ab und der doppelte Anschluss macht den Kartenleser mit nahezu jedem Gerät kompatibel.',
 'Lisez vos cartes SD et microSD directement sur un ordinateur portable, une tablette ou un téléphone. Le boîtier en aluminium dissipe la chaleur et la double connectique rend le lecteur compatible avec presque tous les appareils.'),
('22d08184-409e-46ff-9830-98af6a5f71bb',
 'Work more comfortably with this aluminium laptop stand. The stepless angle adjustment brings your screen to eye level and the open construction provides extra cooling. Foldable and light, ideal for working from home and on the move.',
 'Arbeiten Sie bequemer mit diesem Laptopständer aus Aluminium. Die stufenlose Winkelverstellung bringt den Bildschirm auf Augenhöhe und die offene Konstruktion sorgt für zusätzliche Kühlung. Faltbar und leicht – ideal für Homeoffice und unterwegs.',
 'Travaillez plus confortablement avec ce support d''ordinateur portable en aluminium. Le réglage d''angle en continu place l''écran à hauteur des yeux et la structure ouverte assure un refroidissement supplémentaire. Pliable et léger, idéal au bureau comme en déplacement.')
)
UPDATE public.products p
SET translations = COALESCE(p.translations, '{}'::jsonb)
  || jsonb_build_object(
       'en', COALESCE(p.translations->'en', '{}'::jsonb) || jsonb_build_object('full_description', t.en),
       'de', COALESCE(p.translations->'de', '{}'::jsonb) || jsonb_build_object('full_description', t.de),
       'fr', COALESCE(p.translations->'fr', '{}'::jsonb) || jsonb_build_object('full_description', t.fr)
     )
FROM t
WHERE p.id = t.id;