// Originally generated by the Lovable Supabase integration.
//
// Modified: attaching a session token is best-effort. This runs as a global
// client middleware on every server function, so when Supabase is not
// configured — a fresh checkout, CI, a preview build — the original version
// threw here and no server function could run at all, taking the public
// catalogue down with it. A guest browsing the shop has no session to attach,
// so a missing or failing client now simply means "no token".
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token: string | undefined;
    try {
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token;
    } catch {
      // Supabase unconfigured or unreachable: continue unauthenticated.
      // Protected server functions still reject the request server-side via
      // requireSupabaseAuth, so this cannot be used to bypass authorisation.
      token = undefined;
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
