/**
 * NL/EN/DE/FR content for the catalogue bundled with the application.
 *
 * Supabase is the production catalogue and carries its own `translations`
 * column. This file is the same thing for the fallback catalogue the shop
 * serves when Supabase is not configured — a fresh checkout, CI, a preview
 * build or an outage. Without it, switching to English, German or French left
 * every product name, every category and every brand description in Dutch,
 * so the interface translated around content that did not.
 *
 * Dutch is not repeated here. It lives in catalogue.generated.ts as the base
 * text, and `localize()` falls back to it for any field a language is missing
 * — so a gap shows the Dutch original, never an empty string or a key.
 *
 * Generated by scripts/build_catalogue_translations.py from translations
 * written by hand. They are written, not machine-produced: a mistranslated
 * product name is a description of something the customer is not buying.
 */

import type { Translations } from "@/lib/content-i18n";

/** Keyed by category slug. */
export const CATALOGUE_CATEGORY_TRANSLATIONS: Record<string, Translations> = {
  "kamperen-outdoor": {
    en: {
      name: "Camping & Outdoor",
      description:
        "Torches, head torches and lighting for the road, the campsite and the emergency kit.",
    },
    de: {
      name: "Camping & Outdoor",
      description:
        "Taschenlampen, Stirnlampen und Beleuchtung für unterwegs, den Campingplatz und das Notfallset.",
    },
    fr: {
      name: "Camping et plein air",
      description:
        "Lampes de poche, lampes frontales et éclairage pour la route, le camping et le kit d'urgence.",
    },
  },
  badkamer: {
    en: {
      name: "Bathroom",
      description: "Shower heads, hoses and filters for more comfort in the shower.",
    },
    de: {
      name: "Bad",
      description: "Duschköpfe, Duschschläuche und Filter für mehr Komfort unter der Dusche.",
    },
    fr: {
      name: "Salle de bains",
      description: "Pommeaux de douche, flexibles et filtres pour plus de confort sous la douche.",
    },
  },
  "persoonlijke-verzorging": {
    en: {
      name: "Personal care",
      description: "Airstylers, hot brushes and grooming products for everyday use.",
    },
    de: {
      name: "Körperpflege",
      description: "Airstyler, Warmluftbürsten und Pflegeprodukte für den täglichen Gebrauch.",
    },
    fr: {
      name: "Soins personnels",
      description:
        "Brosses soufflantes, brosses chauffantes et produits de soin pour un usage quotidien.",
    },
  },
  "lifestyle-accessoires": {
    en: {
      name: "Lifestyle & Accessories",
      description:
        "Aluminium cigarette cases and accessories with a sturdy, weather-resistant finish.",
    },
    de: {
      name: "Lifestyle & Accessoires",
      description:
        "Zigarettenetuis aus Aluminium und Accessoires mit robuster, wetterfester Verarbeitung.",
    },
    fr: {
      name: "Lifestyle et accessoires",
      description:
        "Étuis à cigarettes en aluminium et accessoires à la finition robuste et résistante aux intempéries.",
    },
  },
  "klussen-huis": {
    en: {
      name: "DIY & Home",
      description: "Wireless doorbells and household solutions that install in minutes.",
    },
    de: {
      name: "Heimwerken & Haushalt",
      description: "Funktürklingeln und Haushaltslösungen, die im Handumdrehen installiert sind.",
    },
    fr: {
      name: "Bricolage et maison",
      description:
        "Sonnettes sans fil et solutions domestiques qui s'installent en quelques minutes.",
    },
  },
  "elektronica-accessoires": {
    en: {
      name: "Electronics & Accessories",
      description: "Adapters, card readers and laptop stands for home and the office.",
    },
    de: {
      name: "Elektronik & Zubehör",
      description: "Adapter, Kartenleser und Laptopständer für zu Hause und fürs Büro.",
    },
    fr: {
      name: "Électronique et accessoires",
      description:
        "Adaptateurs, lecteurs de cartes et supports pour ordinateur portable, à la maison comme au bureau.",
    },
  },
  "auto-fiets-reizen": {
    en: {
      name: "Car, Bike & Travel",
      description: "Phone mounts and travel adaptors for the car, the bike and the trip.",
    },
    de: {
      name: "Auto, Fahrrad & Reise",
      description: "Handyhalterungen und Reisestecker für Auto, Fahrrad und unterwegs.",
    },
    fr: {
      name: "Voiture, vélo et voyage",
      description:
        "Supports de téléphone et adaptateurs de voyage pour la voiture, le vélo et les déplacements.",
    },
  },
  tuin: {
    en: {
      name: "Garden",
      description:
        "Solar outdoor lighting and grow lights for the garden, the balcony and houseplants.",
    },
    de: {
      name: "Garten",
      description:
        "Solar-Außenbeleuchtung und Pflanzenlampen für Garten, Balkon und Zimmerpflanzen.",
    },
    fr: {
      name: "Jardin",
      description:
        "Éclairage extérieur solaire et lampes de croissance pour le jardin, le balcon et les plantes d'intérieur.",
    },
  },
  "koken-tafelen": {
    en: {
      name: "Cooking & Dining",
      description: "Digital kitchen scales for weighing accurately while cooking and baking.",
    },
    de: {
      name: "Kochen & Tafeln",
      description: "Digitale Küchenwaagen zum genauen Abwiegen beim Kochen und Backen.",
    },
    fr: {
      name: "Cuisine et table",
      description:
        "Balances de cuisine numériques pour peser avec précision en cuisinant et en pâtissant.",
    },
  },
  "creatief-hobby": {
    en: {
      name: "Creative & Hobby",
      description: "Double-ended alcohol markers for drawing, illustration and hand lettering.",
    },
    de: {
      name: "Kreativ & Hobby",
      description: "Doppelseitige Alkoholmarker zum Zeichnen, Illustrieren und Handlettering.",
    },
    fr: {
      name: "Loisirs créatifs",
      description:
        "Marqueurs à alcool double pointe pour le dessin, l'illustration et le lettrage.",
    },
  },
};

/** Keyed by brand slug. Brand names are proper nouns and are not translated. */
export const CATALOGUE_BRAND_TRANSLATIONS: Record<string, Translations> = {
  besjaar: {
    en: {
      description:
        "The shop's own brand. Besjaar stands for practical products for the home, bathroom, garden and the road — lighting, shower comfort and useful household items.",
    },
    de: {
      description:
        "Die Eigenmarke des Shops. Besjaar steht für praktische Produkte für Haus, Bad, Garten und unterwegs — Beleuchtung, Duschkomfort und nützliche Haushaltsartikel.",
    },
    fr: {
      description:
        "La marque propre de la boutique. Besjaar, ce sont des produits pratiques pour la maison, la salle de bains, le jardin et les déplacements : éclairage, confort sous la douche et articles ménagers utiles.",
    },
  },
  rynex: {
    en: {
      description:
        "RYNEX supplies accessories for the desk, the kitchen, the car and the bike: phone mounts, adapters, card readers, scales and hobby materials.",
    },
    de: {
      description:
        "RYNEX liefert Zubehör für Arbeitsplatz, Küche, Auto und Fahrrad: Handyhalterungen, Adapter, Kartenleser, Waagen und Hobbymaterial.",
    },
    fr: {
      description:
        "RYNEX propose des accessoires pour le bureau, la cuisine, la voiture et le vélo : supports de téléphone, adaptateurs, lecteurs de cartes, balances et matériel de loisirs créatifs.",
    },
  },
  lynex: {
    en: {
      description:
        "LYNEX focuses on personal care, with airstylers and hot brushes for styling hair.",
    },
    de: {
      description:
        "LYNEX konzentriert sich auf die Körperpflege, mit Airstylern und Warmluftbürsten zum Stylen der Haare.",
    },
    fr: {
      description:
        "LYNEX se consacre aux soins personnels, avec des brosses soufflantes et chauffantes pour coiffer les cheveux.",
    },
  },
};

/** Keyed by product slug. */
export const CATALOGUE_PRODUCT_TRANSLATIONS: Record<string, Translations> = {
  "besjaar-hoofdlamp-led-oplaadbaar-1000-lumen": {
    en: {
      name: "LED Head Torch, Rechargeable – 1000 Lumen",
      short_description:
        "Rechargeable LED head torch with 8 LED lamps, 1000 lumens and a 100-metre beam, in black.",
      full_description:
        "Rechargeable LED head torch with 8 LED lamps, 1000 lumens and a 100-metre beam, in black.",
    },
    de: {
      name: "LED-Stirnlampe, wiederaufladbar – 1000 Lumen",
      short_description:
        "Wiederaufladbare LED-Stirnlampe mit 8 LED-Leuchten, 1000 Lumen und 100 Metern Reichweite, in Schwarz.",
      full_description:
        "Wiederaufladbare LED-Stirnlampe mit 8 LED-Leuchten, 1000 Lumen und 100 Metern Reichweite, in Schwarz.",
    },
    fr: {
      name: "Lampe frontale LED rechargeable – 1000 lumens",
      short_description:
        "Lampe frontale LED rechargeable à 8 LED, 1000 lumens et 100 mètres de portée, en noir.",
      full_description:
        "Lampe frontale LED rechargeable à 8 LED, 1000 lumens et 100 mètres de portée, en noir.",
    },
  },
  "besjaar-hoofdlamp-led-oplaadbaar-400-lumen": {
    en: {
      name: "LED Head Torch, Rechargeable – 400 Lumen",
      short_description:
        "Rechargeable head torch with a motion sensor, six light modes, 400 lumens and USB-C charging.",
      full_description:
        "Rechargeable head torch with a motion sensor, six light modes, 400 lumens and USB-C charging.",
    },
    de: {
      name: "LED-Stirnlampe, wiederaufladbar – 400 Lumen",
      short_description:
        "Wiederaufladbare Stirnlampe mit Bewegungssensor, sechs Lichtstufen, 400 Lumen und USB-C-Ladung.",
      full_description:
        "Wiederaufladbare Stirnlampe mit Bewegungssensor, sechs Lichtstufen, 400 Lumen und USB-C-Ladung.",
    },
    fr: {
      name: "Lampe frontale LED rechargeable – 400 lumens",
      short_description:
        "Lampe frontale rechargeable avec détecteur de mouvement, six modes d'éclairage, 400 lumens et charge USB-C.",
      full_description:
        "Lampe frontale rechargeable avec détecteur de mouvement, six modes d'éclairage, 400 lumens et charge USB-C.",
    },
  },
  "besjaar-krachtige-militaire-zaklamp": {
    en: {
      name: "Powerful Tactical Torch",
      short_description: "Powerful tactical torch, IP65 water-resistant and battery-powered.",
      full_description: "Powerful tactical torch, IP65 water-resistant and battery-powered.",
    },
    de: {
      name: "Kraftvolle Taktik-Taschenlampe",
      short_description:
        "Kraftvolle taktische Taschenlampe, nach IP65 wasserdicht und batteriebetrieben.",
      full_description:
        "Kraftvolle taktische Taschenlampe, nach IP65 wasserdicht und batteriebetrieben.",
    },
    fr: {
      name: "Lampe torche tactique puissante",
      short_description: "Lampe torche tactique puissante, étanche IP65 et alimentée par piles.",
      full_description: "Lampe torche tactique puissante, étanche IP65 et alimentée par piles.",
    },
  },
  "besjaar-lichtgewicht-hoofdlamp-led-oplaadbaar": {
    en: {
      name: "Lightweight LED Head Torch, Rechargeable",
      short_description:
        "Lightweight rechargeable LED head torch, comfortable enough to wear all evening.",
      full_description:
        "Lightweight rechargeable LED head torch, comfortable enough to wear all evening.",
    },
    de: {
      name: "Leichte LED-Stirnlampe, wiederaufladbar",
      short_description:
        "Leichte wiederaufladbare LED-Stirnlampe, bequem genug für den ganzen Abend.",
      full_description:
        "Leichte wiederaufladbare LED-Stirnlampe, bequem genug für den ganzen Abend.",
    },
    fr: {
      name: "Lampe frontale LED légère, rechargeable",
      short_description:
        "Lampe frontale LED rechargeable et légère, assez confortable pour toute une soirée.",
      full_description:
        "Lampe frontale LED rechargeable et légère, assez confortable pour toute une soirée.",
    },
  },
  "besjaar-militaire-zaklamp-2000-lumen": {
    en: {
      name: "Tactical Torch – 2000 Lumen",
      short_description: "Tactical torch delivering 2000 lumens for outdoor use and emergencies.",
      full_description: "Tactical torch delivering 2000 lumens for outdoor use and emergencies.",
    },
    de: {
      name: "Taktik-Taschenlampe – 2000 Lumen",
      short_description: "Taktische Taschenlampe mit 2000 Lumen für draußen und für den Notfall.",
      full_description: "Taktische Taschenlampe mit 2000 Lumen für draußen und für den Notfall.",
    },
    fr: {
      name: "Lampe torche tactique – 2000 lumens",
      short_description: "Lampe torche tactique de 2000 lumens pour l'extérieur et les urgences.",
      full_description: "Lampe torche tactique de 2000 lumens pour l'extérieur et les urgences.",
    },
  },
  "besjaar-militaire-zaklamp-incl-batterijen": {
    en: {
      name: "Tactical Torch – Batteries Included",
      short_description: "Tactical torch supplied with batteries, ready to use out of the box.",
      full_description: "Tactical torch supplied with batteries, ready to use out of the box.",
    },
    de: {
      name: "Taktik-Taschenlampe – inkl. Batterien",
      short_description: "Taktische Taschenlampe inklusive Batterien, sofort einsatzbereit.",
      full_description: "Taktische Taschenlampe inklusive Batterien, sofort einsatzbereit.",
    },
    fr: {
      name: "Lampe torche tactique – piles incluses",
      short_description: "Lampe torche tactique livrée avec ses piles, prête à l'emploi.",
      full_description: "Lampe torche tactique livrée avec ses piles, prête à l'emploi.",
    },
  },
  "besjaar-militaire-zaklamp-op-batterijen": {
    en: {
      name: "Tactical Torch – Battery Powered",
      short_description: "Battery-powered tactical torch, with no charging to remember.",
      full_description: "Battery-powered tactical torch, with no charging to remember.",
    },
    de: {
      name: "Taktik-Taschenlampe – Batteriebetrieb",
      short_description: "Batteriebetriebene taktische Taschenlampe, ganz ohne Aufladen.",
      full_description: "Batteriebetriebene taktische Taschenlampe, ganz ohne Aufladen.",
    },
    fr: {
      name: "Lampe torche tactique – à piles",
      short_description: "Lampe torche tactique à piles, sans recharge à prévoir.",
      full_description: "Lampe torche tactique à piles, sans recharge à prévoir.",
    },
  },
  "besjaar-opwindbare-zaklamp": {
    en: {
      name: "Wind-Up Torch",
      short_description:
        "Wind-up torch that needs no batteries — useful in the emergency kit and on the road.",
      full_description:
        "Wind-up torch that needs no batteries — useful in the emergency kit and on the road.",
    },
    de: {
      name: "Kurbel-Taschenlampe",
      short_description:
        "Kurbel-Taschenlampe ganz ohne Batterien — praktisch im Notfallset und unterwegs.",
      full_description:
        "Kurbel-Taschenlampe ganz ohne Batterien — praktisch im Notfallset und unterwegs.",
    },
    fr: {
      name: "Lampe torche à dynamo",
      short_description:
        "Lampe torche à manivelle qui ne nécessite aucune pile : idéale dans le kit d'urgence et en déplacement.",
      full_description:
        "Lampe torche à manivelle qui ne nécessite aucune pile : idéale dans le kit d'urgence et en déplacement.",
    },
  },
  "besjaar-uv-zaklamp-blacklight": {
    en: {
      name: "UV Blacklight Torch",
      short_description: "UV blacklight torch for spotting stains, leaks and counterfeit notes.",
      full_description: "UV blacklight torch for spotting stains, leaks and counterfeit notes.",
    },
    de: {
      name: "UV-Schwarzlicht-Taschenlampe",
      short_description: "UV-Schwarzlichtlampe zum Aufspüren von Flecken, Lecks und Falschgeld.",
      full_description: "UV-Schwarzlichtlampe zum Aufspüren von Flecken, Lecks und Falschgeld.",
    },
    fr: {
      name: "Lampe UV à lumière noire",
      short_description:
        "Lampe torche UV à lumière noire pour repérer taches, fuites et faux billets.",
      full_description:
        "Lampe torche UV à lumière noire pour repérer taches, fuites et faux billets.",
    },
  },
  "besjaar-zaklamp-led-oplaadbaar-10000-lumen": {
    en: {
      name: "LED Torch, Rechargeable – 10000 Lumen",
      short_description:
        "Rechargeable LED torch delivering 10000 lumens, the brightest in the range.",
      full_description:
        "Rechargeable LED torch delivering 10000 lumens, the brightest in the range.",
    },
    de: {
      name: "LED-Taschenlampe, wiederaufladbar – 10000 Lumen",
      short_description:
        "Wiederaufladbare LED-Taschenlampe mit 10000 Lumen — die hellste im Sortiment.",
      full_description:
        "Wiederaufladbare LED-Taschenlampe mit 10000 Lumen — die hellste im Sortiment.",
    },
    fr: {
      name: "Lampe torche LED rechargeable – 10000 lumens",
      short_description:
        "Lampe torche LED rechargeable de 10000 lumens, la plus puissante de la gamme.",
      full_description:
        "Lampe torche LED rechargeable de 10000 lumens, la plus puissante de la gamme.",
    },
  },
  "besjaar-zaklamp-led-oplaadbaar-1200-lumen": {
    en: {
      name: "LED Torch, Rechargeable – 1200 Lumen",
      short_description:
        "Rechargeable LED torch with 1200 lumens for everyday use around the house.",
      full_description:
        "Rechargeable LED torch with 1200 lumens for everyday use around the house.",
    },
    de: {
      name: "LED-Taschenlampe, wiederaufladbar – 1200 Lumen",
      short_description:
        "Wiederaufladbare LED-Taschenlampe mit 1200 Lumen für den Alltag rund ums Haus.",
      full_description:
        "Wiederaufladbare LED-Taschenlampe mit 1200 Lumen für den Alltag rund ums Haus.",
    },
    fr: {
      name: "Lampe torche LED rechargeable – 1200 lumens",
      short_description:
        "Lampe torche LED rechargeable de 1200 lumens pour un usage quotidien à la maison.",
      full_description:
        "Lampe torche LED rechargeable de 1200 lumens pour un usage quotidien à la maison.",
    },
  },
  "besjaar-zaklamp-led-oplaadbaar-5000-lumen": {
    en: {
      name: "LED Torch, Rechargeable – 5000 Lumen",
      short_description: "Rechargeable LED torch with 5000 lumens and a long beam.",
      full_description: "Rechargeable LED torch with 5000 lumens and a long beam.",
    },
    de: {
      name: "LED-Taschenlampe, wiederaufladbar – 5000 Lumen",
      short_description: "Wiederaufladbare LED-Taschenlampe mit 5000 Lumen und großer Reichweite.",
      full_description: "Wiederaufladbare LED-Taschenlampe mit 5000 Lumen und großer Reichweite.",
    },
    fr: {
      name: "Lampe torche LED rechargeable – 5000 lumens",
      short_description: "Lampe torche LED rechargeable de 5000 lumens à longue portée.",
      full_description: "Lampe torche LED rechargeable de 5000 lumens à longue portée.",
    },
  },
  "besjaar-zaklamp-led-oplaadbaar-7400-lumen": {
    en: {
      name: "LED Torch, Rechargeable – 7400 Lumen",
      short_description: "Rechargeable LED torch with 7400 lumens for outdoor work after dark.",
      full_description: "Rechargeable LED torch with 7400 lumens for outdoor work after dark.",
    },
    de: {
      name: "LED-Taschenlampe, wiederaufladbar – 7400 Lumen",
      short_description:
        "Wiederaufladbare LED-Taschenlampe mit 7400 Lumen für Arbeiten im Dunkeln.",
      full_description: "Wiederaufladbare LED-Taschenlampe mit 7400 Lumen für Arbeiten im Dunkeln.",
    },
    fr: {
      name: "Lampe torche LED rechargeable – 7400 lumens",
      short_description:
        "Lampe torche LED rechargeable de 7400 lumens pour travailler dehors une fois la nuit tombée.",
      full_description:
        "Lampe torche LED rechargeable de 7400 lumens pour travailler dehors une fois la nuit tombée.",
    },
  },
  "besjaar-zaklamp-led-oplaadbaar-7800-lumen": {
    en: {
      name: "LED Torch, Rechargeable – 7800 Lumen",
      short_description: "Rechargeable LED torch with 7800 lumens and several light modes.",
      full_description: "Rechargeable LED torch with 7800 lumens and several light modes.",
    },
    de: {
      name: "LED-Taschenlampe, wiederaufladbar – 7800 Lumen",
      short_description:
        "Wiederaufladbare LED-Taschenlampe mit 7800 Lumen und mehreren Lichtstufen.",
      full_description:
        "Wiederaufladbare LED-Taschenlampe mit 7800 Lumen und mehreren Lichtstufen.",
    },
    fr: {
      name: "Lampe torche LED rechargeable – 7800 lumens",
      short_description:
        "Lampe torche LED rechargeable de 7800 lumens et plusieurs modes d'éclairage.",
      full_description:
        "Lampe torche LED rechargeable de 7800 lumens et plusieurs modes d'éclairage.",
    },
  },
  "besjaar-zaklamp-led-oplaadbaar-9000-lumen": {
    en: {
      name: "LED Torch, Rechargeable – 9000 Lumen",
      short_description: "Rechargeable LED torch with 9000 lumens for the darkest jobs.",
      full_description: "Rechargeable LED torch with 9000 lumens for the darkest jobs.",
    },
    de: {
      name: "LED-Taschenlampe, wiederaufladbar – 9000 Lumen",
      short_description:
        "Wiederaufladbare LED-Taschenlampe mit 9000 Lumen für die dunkelsten Aufgaben.",
      full_description:
        "Wiederaufladbare LED-Taschenlampe mit 9000 Lumen für die dunkelsten Aufgaben.",
    },
    fr: {
      name: "Lampe torche LED rechargeable – 9000 lumens",
      short_description:
        "Lampe torche LED rechargeable de 9000 lumens pour les travaux les plus sombres.",
      full_description:
        "Lampe torche LED rechargeable de 9000 lumens pour les travaux les plus sombres.",
    },
  },
  "besjaar-zaklamp-met-ingebouwde-accu": {
    en: {
      name: "Torch with Built-In Battery",
      short_description: "Torch with a built-in rechargeable battery — nothing loose to lose.",
      full_description: "Torch with a built-in rechargeable battery — nothing loose to lose.",
    },
    de: {
      name: "Taschenlampe mit fest eingebautem Akku",
      short_description:
        "Taschenlampe mit fest eingebautem Akku — nichts Loses, das verloren gehen kann.",
      full_description:
        "Taschenlampe mit fest eingebautem Akku — nichts Loses, das verloren gehen kann.",
    },
    fr: {
      name: "Lampe torche à batterie intégrée",
      short_description:
        "Lampe torche à batterie rechargeable intégrée : rien qui puisse se perdre.",
      full_description:
        "Lampe torche à batterie rechargeable intégrée : rien qui puisse se perdre.",
    },
  },
  "besjaar-douchefilter": {
    en: {
      name: "Shower Filter",
      short_description: "Water filter for a shower head, model 1002026, two filters in white.",
      full_description: "Water filter for a shower head, model 1002026, two filters in white.",
    },
    de: {
      name: "Duschfilter",
      short_description: "Wasserfilter für den Duschkopf, Modell 1002026, zwei Filter in Weiß.",
      full_description: "Wasserfilter für den Duschkopf, Modell 1002026, zwei Filter in Weiß.",
    },
    fr: {
      name: "Filtre de douche",
      short_description:
        "Filtre à eau pour pommeau de douche, modèle 1002026, deux filtres, en blanc.",
      full_description:
        "Filtre à eau pour pommeau de douche, modèle 1002026, deux filtres, en blanc.",
    },
  },
  "besjaar-douchekop": {
    en: {
      name: "Shower Head",
      short_description:
        "High-pressure rain shower head with three spray modes, for a wellness shower that is kinder to the skin.",
      full_description:
        "High-pressure rain shower head with three spray modes, for a wellness shower that is kinder to the skin.",
    },
    de: {
      name: "Duschkopf",
      short_description:
        "Hochdruck-Regenduschkopf mit drei Strahlarten, für eine Wellness-Dusche, die die Haut schont.",
      full_description:
        "Hochdruck-Regenduschkopf mit drei Strahlarten, für eine Wellness-Dusche, die die Haut schont.",
    },
    fr: {
      name: "Pommeau de douche",
      short_description:
        "Pommeau de douche pluie haute pression à trois jets, pour une douche bien-être plus douce pour la peau.",
      full_description:
        "Pommeau de douche pluie haute pression à trois jets, pour une douche bien-être plus douce pour la peau.",
    },
  },
  "besjaar-douchekop-met-slang-10-sproeistanden": {
    en: {
      name: "Shower Head with Hose – 10 Spray Modes",
      short_description:
        "High-pressure rain shower head with a filter, ten spray modes and a water-saving hand shower.",
      full_description:
        "High-pressure rain shower head with a filter, ten spray modes and a water-saving hand shower.",
    },
    de: {
      name: "Duschkopf mit Schlauch – 10 Strahlarten",
      short_description:
        "Hochdruck-Regenduschkopf mit Filter, zehn Strahlarten und wassersparender Handbrause.",
      full_description:
        "Hochdruck-Regenduschkopf mit Filter, zehn Strahlarten und wassersparender Handbrause.",
    },
    fr: {
      name: "Pommeau de douche avec flexible – 10 jets",
      short_description:
        "Pommeau de douche pluie haute pression avec filtre, dix jets et douchette économe en eau.",
      full_description:
        "Pommeau de douche pluie haute pression avec filtre, dix jets et douchette économe en eau.",
    },
  },
  "besjaar-douchekop-met-slang-3-sproeistanden": {
    en: {
      name: "Shower Head with Hose – 3 Spray Modes",
      short_description:
        "High-pressure rain shower head with hose and three spray modes, for a wellness shower.",
      full_description:
        "High-pressure rain shower head with hose and three spray modes, for a wellness shower.",
    },
    de: {
      name: "Duschkopf mit Schlauch – 3 Strahlarten",
      short_description:
        "Hochdruck-Regenduschkopf mit Schlauch und drei Strahlarten, für eine Wellness-Dusche.",
      full_description:
        "Hochdruck-Regenduschkopf mit Schlauch und drei Strahlarten, für eine Wellness-Dusche.",
    },
    fr: {
      name: "Pommeau de douche avec flexible – 3 jets",
      short_description:
        "Pommeau de douche pluie haute pression avec flexible et trois jets, pour une douche bien-être.",
      full_description:
        "Pommeau de douche pluie haute pression avec flexible et trois jets, pour une douche bien-être.",
    },
  },
  "besjaar-hoge-druk-douchekop-met-filter": {
    en: {
      name: "High-Pressure Shower Head with Filter",
      short_description: "Model 1002025: ten spray modes, water-saving, in silver.",
      full_description: "Model 1002025: ten spray modes, water-saving, in silver.",
    },
    de: {
      name: "Hochdruck-Duschkopf mit Filter",
      short_description: "Modell 1002025: zehn Strahlarten, wassersparend, in Silber.",
      full_description: "Modell 1002025: zehn Strahlarten, wassersparend, in Silber.",
    },
    fr: {
      name: "Pommeau de douche haute pression avec filtre",
      short_description: "Modèle 1002025 : dix jets, économe en eau, coloris argent.",
      full_description: "Modèle 1002025 : dix jets, économe en eau, coloris argent.",
    },
  },
  "lynex-airstyler": {
    en: {
      name: "Airstyler",
      short_description:
        "Seven-in-one multi styler: curling wand, hot air brush and airstyler in a single tool.",
      full_description:
        "Seven-in-one multi styler: curling wand, hot air brush and airstyler in a single tool.",
    },
    de: {
      name: "Airstyler",
      short_description:
        "Sieben-in-eins-Multistyler: Lockenstab, Warmluftbürste und Airstyler in einem Gerät.",
      full_description:
        "Sieben-in-eins-Multistyler: Lockenstab, Warmluftbürste und Airstyler in einem Gerät.",
    },
    fr: {
      name: "Brosse soufflante",
      short_description:
        "Multi-styler sept-en-un : fer à boucler, brosse soufflante et brosse chauffante en un seul appareil.",
      full_description:
        "Multi-styler sept-en-un : fer à boucler, brosse soufflante et brosse chauffante en un seul appareil.",
    },
  },
  "besjaar-airstyler-krultang-5-in-1": {
    en: {
      name: "Airstyler Curling Wand 5 in 1",
      short_description:
        "Five-in-one multi styler with hot air brush, straightener and hair wrap — the 2026 model.",
      full_description:
        "Five-in-one multi styler with hot air brush, straightener and hair wrap — the 2026 model.",
    },
    de: {
      name: "Airstyler Lockenstab 5 in 1",
      short_description:
        "Fünf-in-eins-Multistyler mit Warmluftbürste, Glätteisen und Hair Wrap — Modelljahr 2026.",
      full_description:
        "Fünf-in-eins-Multistyler mit Warmluftbürste, Glätteisen und Hair Wrap — Modelljahr 2026.",
    },
    fr: {
      name: "Brosse soufflante boucleur 5 en 1",
      short_description:
        "Multi-styler cinq-en-un avec brosse soufflante, lisseur et enrouleur — modèle 2026.",
      full_description:
        "Multi-styler cinq-en-un avec brosse soufflante, lisseur et enrouleur — modèle 2026.",
    },
  },
  "rynex-massage-gun": {
    en: {
      name: "Massage Gun",
      short_description: "Massage gun with six speeds and four heads, supplied in a carry case.",
      full_description: "Massage gun with six speeds and four heads, supplied in a carry case.",
    },
    de: {
      name: "Massagepistole",
      short_description:
        "Massagepistole mit sechs Geschwindigkeiten und vier Aufsätzen, im Transportkoffer.",
      full_description:
        "Massagepistole mit sechs Geschwindigkeiten und vier Aufsätzen, im Transportkoffer.",
    },
    fr: {
      name: "Pistolet de massage",
      short_description:
        "Pistolet de massage à six vitesses et quatre embouts, livré dans sa mallette.",
      full_description:
        "Pistolet de massage à six vitesses et quatre embouts, livré dans sa mallette.",
    },
  },
  "besjaar-multistyler": {
    en: {
      name: "Multistyler",
      short_description:
        "Five-in-one styler combining an airstyler, hot air brush, curling brush, curling wand and straightener.",
      full_description:
        "Five-in-one styler combining an airstyler, hot air brush, curling brush, curling wand and straightener.",
    },
    de: {
      name: "Multistyler",
      short_description:
        "Fünf-in-eins-Styler aus Airstyler, Warmluftbürste, Lockenbürste, Lockenstab und Glätteisen.",
      full_description:
        "Fünf-in-eins-Styler aus Airstyler, Warmluftbürste, Lockenbürste, Lockenstab und Glätteisen.",
    },
    fr: {
      name: "Multi-styler",
      short_description:
        "Styler cinq-en-un réunissant brosse soufflante, brosse chauffante, brosse boucleuse, fer à boucler et lisseur.",
      full_description:
        "Styler cinq-en-un réunissant brosse soufflante, brosse chauffante, brosse boucleuse, fer à boucler et lisseur.",
    },
  },
  "rynex-neusstrips": {
    en: {
      name: "Nasal Strips",
      short_description:
        "Thirty anti-snoring nasal strips that widen the nostrils for easier breathing and better sleep.",
      full_description:
        "Thirty anti-snoring nasal strips that widen the nostrils for easier breathing and better sleep.",
    },
    de: {
      name: "Nasenstrips",
      short_description:
        "Dreißig Anti-Schnarch-Nasenstrips, die die Nasenflügel weiten — leichter atmen, besser schlafen.",
      full_description:
        "Dreißig Anti-Schnarch-Nasenstrips, die die Nasenflügel weiten — leichter atmen, besser schlafen.",
    },
    fr: {
      name: "Bandelettes nasales",
      short_description:
        "Trente bandelettes nasales anti-ronflement qui élargissent les narines pour mieux respirer et mieux dormir.",
      full_description:
        "Trente bandelettes nasales anti-ronflement qui élargissent les narines pour mieux respirer et mieux dormir.",
    },
  },
  "rynex-pimple-patch": {
    en: {
      name: "Pimple Patches",
      short_description: "144 hydrocolloid patches that draw out a spot overnight.",
      full_description: "144 hydrocolloid patches that draw out a spot overnight.",
    },
    de: {
      name: "Pickelpflaster",
      short_description: "144 Hydrokolloid-Pflaster, die einen Pickel über Nacht abklingen lassen.",
      full_description: "144 Hydrokolloid-Pflaster, die einen Pickel über Nacht abklingen lassen.",
    },
    fr: {
      name: "Patchs anti-boutons",
      short_description:
        "144 patchs hydrocolloïdes qui font disparaître un bouton pendant la nuit.",
      full_description: "144 patchs hydrocolloïdes qui font disparaître un bouton pendant la nuit.",
    },
  },
  "lynex-thermal-brush": {
    en: {
      name: "Thermal Brush",
      short_description:
        "Ceramic hot brush that dries and styles in one pass — an alternative to a hairdryer and airstyler.",
      full_description:
        "Ceramic hot brush that dries and styles in one pass — an alternative to a hairdryer and airstyler.",
    },
    de: {
      name: "Thermobürste",
      short_description:
        "Keramik-Warmluftbürste, die in einem Durchgang trocknet und stylt — eine Alternative zu Föhn und Airstyler.",
      full_description:
        "Keramik-Warmluftbürste, die in einem Durchgang trocknet und stylt — eine Alternative zu Föhn und Airstyler.",
    },
    fr: {
      name: "Brosse chauffante",
      short_description:
        "Brosse chauffante céramique qui sèche et coiffe en un seul passage — une alternative au sèche-cheveux et à la brosse soufflante.",
      full_description:
        "Brosse chauffante céramique qui sèche et coiffe en un seul passage — une alternative au sèche-cheveux et à la brosse soufflante.",
    },
  },
  "besjaar-sigarettendoosje-zilver": {
    en: {
      name: "Cigarette Case – Silver",
      short_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in silver.",
      full_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in silver.",
    },
    de: {
      name: "Zigarettenetui – Silber",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Silber.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Silber.",
    },
    fr: {
      name: "Étui à cigarettes – argent",
      short_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris argent.",
      full_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris argent.",
    },
  },
  "besjaar-sigarettendoosjes-met-aansteker": {
    en: {
      name: "Cigarette Cases with Lighter",
      short_description:
        "Sturdy aluminium cigarette case with a built-in lighter and a weather-resistant finish.",
      full_description:
        "Sturdy aluminium cigarette case with a built-in lighter and a weather-resistant finish.",
    },
    de: {
      name: "Zigarettenetuis mit Feuerzeug",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit integriertem Feuerzeug und wetterfester Verarbeitung.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit integriertem Feuerzeug und wetterfester Verarbeitung.",
    },
    fr: {
      name: "Étuis à cigarettes avec briquet",
      short_description:
        "Étui à cigarettes robuste en aluminium avec briquet intégré et finition résistante aux intempéries.",
      full_description:
        "Étui à cigarettes robuste en aluminium avec briquet intégré et finition résistante aux intempéries.",
    },
  },
  "besjaar-sigarettendoosjes-met-aansteker-goud": {
    en: {
      name: "Cigarette Cases with Lighter – Gold",
      short_description: "Sturdy aluminium cigarette case with a built-in lighter, in gold.",
      full_description: "Sturdy aluminium cigarette case with a built-in lighter, in gold.",
    },
    de: {
      name: "Zigarettenetuis mit Feuerzeug – Gold",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit integriertem Feuerzeug, in Gold.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit integriertem Feuerzeug, in Gold.",
    },
    fr: {
      name: "Étuis à cigarettes avec briquet – or",
      short_description: "Étui à cigarettes robuste en aluminium avec briquet intégré, coloris or.",
      full_description: "Étui à cigarettes robuste en aluminium avec briquet intégré, coloris or.",
    },
  },
  "besjaar-sigarettendoosjes-met-aansteker-zilver": {
    en: {
      name: "Cigarette Cases with Lighter – Silver",
      short_description: "Sturdy aluminium cigarette case with a built-in lighter, in silver.",
      full_description: "Sturdy aluminium cigarette case with a built-in lighter, in silver.",
    },
    de: {
      name: "Zigarettenetuis mit Feuerzeug – Silber",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit integriertem Feuerzeug, in Silber.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit integriertem Feuerzeug, in Silber.",
    },
    fr: {
      name: "Étuis à cigarettes avec briquet – argent",
      short_description:
        "Étui à cigarettes robuste en aluminium avec briquet intégré, coloris argent.",
      full_description:
        "Étui à cigarettes robuste en aluminium avec briquet intégré, coloris argent.",
    },
  },
  "besjaar-sigarettendoosjes-goud": {
    en: {
      name: "Cigarette Cases – Gold",
      short_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in gold.",
      full_description: "Sturdy aluminium cigarette case with a weather-resistant finish, in gold.",
    },
    de: {
      name: "Zigarettenetuis – Gold",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Gold.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Gold.",
    },
    fr: {
      name: "Étuis à cigarettes – or",
      short_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris or.",
      full_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris or.",
    },
  },
  "besjaar-sigarettendoosjes-zwart": {
    en: {
      name: "Cigarette Cases – Black",
      short_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in black.",
      full_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in black.",
    },
    de: {
      name: "Zigarettenetuis – Schwarz",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Schwarz.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Schwarz.",
    },
    fr: {
      name: "Étuis à cigarettes – noir",
      short_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris noir.",
      full_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris noir.",
    },
  },
  "besjaar-sigarettendoosjes-zwart-art-7946": {
    en: {
      name: "Cigarette Cases – Black (item 7946)",
      short_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in black.",
      full_description:
        "Sturdy aluminium cigarette case with a weather-resistant finish, in black.",
    },
    de: {
      name: "Zigarettenetuis – Schwarz (Art. 7946)",
      short_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Schwarz.",
      full_description:
        "Robustes Zigarettenetui aus Aluminium mit wetterfester Verarbeitung, in Schwarz.",
    },
    fr: {
      name: "Étuis à cigarettes – noir (réf. 7946)",
      short_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris noir.",
      full_description:
        "Étui à cigarettes robuste en aluminium à la finition résistante aux intempéries, coloris noir.",
    },
  },
  "besjaar-deurbel-draadloos-2-ontvangers": {
    en: {
      name: "Wireless Doorbell – 2 Receivers",
      short_description:
        "Wireless doorbell with two battery-powered receivers, so you hear it upstairs as well.",
      full_description:
        "Wireless doorbell with two battery-powered receivers, so you hear it upstairs as well.",
    },
    de: {
      name: "Funktürklingel – 2 Empfänger",
      short_description:
        "Funktürklingel mit zwei batteriebetriebenen Empfängern, damit man sie auch oben hört.",
      full_description:
        "Funktürklingel mit zwei batteriebetriebenen Empfängern, damit man sie auch oben hört.",
    },
    fr: {
      name: "Sonnette sans fil – 2 récepteurs",
      short_description:
        "Sonnette sans fil avec deux récepteurs à piles, pour l'entendre aussi à l'étage.",
      full_description:
        "Sonnette sans fil avec deux récepteurs à piles, pour l'entendre aussi à l'étage.",
    },
  },
  "besjaar-deurbel-draadloos-zwart": {
    en: {
      name: "Wireless Doorbell – Black",
      short_description: "Wireless doorbell, IP44 rated and supplied with batteries, in black.",
      full_description: "Wireless doorbell, IP44 rated and supplied with batteries, in black.",
    },
    de: {
      name: "Funktürklingel – Schwarz",
      short_description: "Funktürklingel nach IP44, inklusive Batterien, in Schwarz.",
      full_description: "Funktürklingel nach IP44, inklusive Batterien, in Schwarz.",
    },
    fr: {
      name: "Sonnette sans fil – noir",
      short_description: "Sonnette sans fil certifiée IP44, piles incluses, coloris noir.",
      full_description: "Sonnette sans fil certifiée IP44, piles incluses, coloris noir.",
    },
  },
  "rynex-muizenval-6-stuks": {
    en: {
      name: "Mouse Traps – 6 Pack",
      short_description: "Six mouse traps for indoors and outdoors — an alternative to poison.",
      full_description: "Six mouse traps for indoors and outdoors — an alternative to poison.",
    },
    de: {
      name: "Mausefallen – 6 Stück",
      short_description: "Sechs Mausefallen für drinnen und draußen — eine Alternative zu Gift.",
      full_description: "Sechs Mausefallen für drinnen und draußen — eine Alternative zu Gift.",
    },
    fr: {
      name: "Pièges à souris – lot de 6",
      short_description:
        "Six pièges à souris pour l'intérieur et l'extérieur — une alternative au poison.",
      full_description:
        "Six pièges à souris pour l'intérieur et l'extérieur — une alternative au poison.",
    },
  },
  "rynex-muizenval-6-stuks-muizenklem": {
    en: {
      name: "Mouse Traps – 6 Pack, Snap Trap",
      short_description: "Six snap traps for indoors and outdoors — an alternative to poison.",
      full_description: "Six snap traps for indoors and outdoors — an alternative to poison.",
    },
    de: {
      name: "Mausefallen – 6 Stück, Schlagfalle",
      short_description: "Sechs Schlagfallen für drinnen und draußen — eine Alternative zu Gift.",
      full_description: "Sechs Schlagfallen für drinnen und draußen — eine Alternative zu Gift.",
    },
    fr: {
      name: "Pièges à souris – lot de 6, tapette",
      short_description:
        "Six tapettes à souris pour l'intérieur et l'extérieur — une alternative au poison.",
      full_description:
        "Six tapettes à souris pour l'intérieur et l'extérieur — une alternative au poison.",
    },
  },
  "rynex-3x-usb-c-naar-usb-a-adapter-otg-3-0": {
    en: {
      name: "3x USB-C to USB-A OTG 3.0 Adapter",
      short_description: "Three USB-C to USB-A female converters with OTG 3.0 support, in black.",
      full_description: "Three USB-C to USB-A female converters with OTG 3.0 support, in black.",
    },
    de: {
      name: "3x USB-C-auf-USB-A-Adapter OTG 3.0",
      short_description:
        "Drei Adapter von USB-C auf USB-A (Buchse) mit OTG-3.0-Unterstützung, in Schwarz.",
      full_description:
        "Drei Adapter von USB-C auf USB-A (Buchse) mit OTG-3.0-Unterstützung, in Schwarz.",
    },
    fr: {
      name: "3x adaptateur USB-C vers USB-A OTG 3.0",
      short_description:
        "Trois convertisseurs USB-C vers USB-A femelle compatibles OTG 3.0, coloris noir.",
      full_description:
        "Trois convertisseurs USB-C vers USB-A femelle compatibles OTG 3.0, coloris noir.",
    },
  },
  "rynex-aluminium-laptop-standaard": {
    en: {
      name: "Aluminium Laptop Stand",
      short_description:
        "Adjustable ergonomic aluminium laptop stand for home and the office, in silver.",
      full_description:
        "Adjustable ergonomic aluminium laptop stand for home and the office, in silver.",
    },
    de: {
      name: "Aluminium-Laptopständer",
      short_description:
        "Verstellbarer ergonomischer Laptopständer aus Aluminium für zu Hause und fürs Büro, in Silber.",
      full_description:
        "Verstellbarer ergonomischer Laptopständer aus Aluminium für zu Hause und fürs Büro, in Silber.",
    },
    fr: {
      name: "Support d'ordinateur portable en aluminium",
      short_description:
        "Support ergonomique réglable en aluminium pour ordinateur portable, à la maison comme au bureau, coloris argent.",
      full_description:
        "Support ergonomique réglable en aluminium pour ordinateur portable, à la maison comme au bureau, coloris argent.",
    },
  },
  "rynex-sd-kaart-lezer": {
    en: {
      name: "SD Card Reader",
      short_description:
        "Three-in-one SD, TF and USB 3.0 card reader with USB-C, converter included.",
      full_description:
        "Three-in-one SD, TF and USB 3.0 card reader with USB-C, converter included.",
    },
    de: {
      name: "SD-Kartenleser",
      short_description:
        "Drei-in-eins-Kartenleser für SD, TF und USB 3.0 mit USB-C, Adapter inklusive.",
      full_description:
        "Drei-in-eins-Kartenleser für SD, TF und USB 3.0 mit USB-C, Adapter inklusive.",
    },
    fr: {
      name: "Lecteur de carte SD",
      short_description:
        "Lecteur de cartes trois-en-un SD, TF et USB 3.0 avec USB-C, convertisseur inclus.",
      full_description:
        "Lecteur de cartes trois-en-un SD, TF et USB 3.0 avec USB-C, convertisseur inclus.",
    },
  },
  "rynex-telefoonhouder-fiets": {
    en: {
      name: "Bike Phone Mount",
      short_description:
        "Phone mount for bike, scooter and motorbike, rotating 360° with anti-shock damping.",
      full_description:
        "Phone mount for bike, scooter and motorbike, rotating 360° with anti-shock damping.",
    },
    de: {
      name: "Fahrrad-Handyhalterung",
      short_description:
        "Handyhalterung für Fahrrad, Roller und Motorrad, um 360° drehbar und stoßgedämpft.",
      full_description:
        "Handyhalterung für Fahrrad, Roller und Motorrad, um 360° drehbar und stoßgedämpft.",
    },
    fr: {
      name: "Support téléphone vélo",
      short_description:
        "Support de téléphone pour vélo, scooter et moto, rotatif à 360° et anti-vibrations.",
      full_description:
        "Support de téléphone pour vélo, scooter et moto, rotatif à 360° et anti-vibrations.",
    },
  },
  "rynex-telefoonhouders-auto-ventilatie": {
    en: {
      name: "Car Vent Phone Mounts",
      short_description:
        "Universal phone mount for the car's air vent, rotating 360° and holding firm.",
      full_description:
        "Universal phone mount for the car's air vent, rotating 360° and holding firm.",
    },
    de: {
      name: "Auto-Lüftungs-Handyhalterungen",
      short_description:
        "Universelle Handyhalterung für die Lüftung im Auto, um 360° drehbar und fest sitzend.",
      full_description:
        "Universelle Handyhalterung für die Lüftung im Auto, um 360° drehbar und fest sitzend.",
    },
    fr: {
      name: "Supports téléphone pour grille d'aération",
      short_description:
        "Support de téléphone universel pour grille d'aération, rotatif à 360° et bien maintenu.",
      full_description:
        "Support de téléphone universel pour grille d'aération, rotatif à 360° et bien maintenu.",
    },
  },
  "rynex-universele-wereldstekker": {
    en: {
      name: "Universal Travel Adaptor",
      short_description:
        "Universal travel adaptor for more than 150 countries, with USB-C and USB ports.",
      full_description:
        "Universal travel adaptor for more than 150 countries, with USB-C and USB ports.",
    },
    de: {
      name: "Universal-Reisestecker",
      short_description:
        "Universeller Reisestecker für über 150 Länder, mit USB-C- und USB-Anschluss.",
      full_description:
        "Universeller Reisestecker für über 150 Länder, mit USB-C- und USB-Anschluss.",
    },
    fr: {
      name: "Adaptateur de voyage universel",
      short_description:
        "Adaptateur de voyage universel pour plus de 150 pays, avec ports USB-C et USB.",
      full_description:
        "Adaptateur de voyage universel pour plus de 150 pays, avec ports USB-C et USB.",
    },
  },
  "besjaar-kweeklamp-led-voor-planten": {
    en: {
      name: "LED Grow Light for Plants",
      short_description: "Four 40 W grow lights with 80 LEDs each, for houseplants and seedlings.",
      full_description: "Four 40 W grow lights with 80 LEDs each, for houseplants and seedlings.",
    },
    de: {
      name: "LED-Pflanzenlampe",
      short_description:
        "Vier Pflanzenlampen mit je 80 LEDs und 40 W, für Zimmerpflanzen und Anzuchten.",
      full_description:
        "Vier Pflanzenlampen mit je 80 LEDs und 40 W, für Zimmerpflanzen und Anzuchten.",
    },
    fr: {
      name: "Lampe de croissance LED pour plantes",
      short_description:
        "Quatre lampes de croissance de 40 W à 80 LED chacune, pour plantes d'intérieur et semis.",
      full_description:
        "Quatre lampes de croissance de 40 W à 80 LED chacune, pour plantes d'intérieur et semis.",
    },
  },
  "besjaar-solar-buitenverlichting": {
    en: {
      name: "Solar Outdoor Lighting",
      short_description:
        "Solar wall light with a motion sensor, IP65 rated, for the garden and the drive.",
      full_description:
        "Solar wall light with a motion sensor, IP65 rated, for the garden and the drive.",
    },
    de: {
      name: "Solar-Außenbeleuchtung",
      short_description:
        "Solar-Wandleuchte mit Bewegungssensor, nach IP65, für Garten und Einfahrt.",
      full_description:
        "Solar-Wandleuchte mit Bewegungssensor, nach IP65, für Garten und Einfahrt.",
    },
    fr: {
      name: "Éclairage extérieur solaire",
      short_description:
        "Applique solaire à détecteur de mouvement, certifiée IP65, pour le jardin et l'allée.",
      full_description:
        "Applique solaire à détecteur de mouvement, certifiée IP65, pour le jardin et l'allée.",
    },
  },
  "rynex-keukenweegschaal-digitaal-incl-batterijen": {
    en: {
      name: "Digital Kitchen Scale – Batteries Included",
      short_description:
        "Precision kitchen scale up to 10 kg with an LCD display and tare function, batteries included.",
      full_description:
        "Precision kitchen scale up to 10 kg with an LCD display and tare function, batteries included.",
    },
    de: {
      name: "Digitale Küchenwaage – inkl. Batterien",
      short_description:
        "Präzisions-Küchenwaage bis 10 kg mit LCD-Display und Tara-Funktion, Batterien inklusive.",
      full_description:
        "Präzisions-Küchenwaage bis 10 kg mit LCD-Display und Tara-Funktion, Batterien inklusive.",
    },
    fr: {
      name: "Balance de cuisine numérique – piles incluses",
      short_description:
        "Balance de cuisine de précision jusqu'à 10 kg, écran LCD et fonction tare, piles incluses.",
      full_description:
        "Balance de cuisine de précision jusqu'à 10 kg, écran LCD et fonction tare, piles incluses.",
    },
  },
  "rynex-keukenweegschaal-digitaal-tot-10-kg": {
    en: {
      name: "Digital Kitchen Scale – up to 10 kg",
      short_description:
        "Kitchen scale weighing up to 10 kg, with a tare function and batteries included.",
      full_description:
        "Kitchen scale weighing up to 10 kg, with a tare function and batteries included.",
    },
    de: {
      name: "Digitale Küchenwaage – bis 10 kg",
      short_description: "Küchenwaage bis 10 kg, mit Tara-Funktion und Batterien.",
      full_description: "Küchenwaage bis 10 kg, mit Tara-Funktion und Batterien.",
    },
    fr: {
      name: "Balance de cuisine numérique – jusqu'à 10 kg",
      short_description: "Balance de cuisine jusqu'à 10 kg, avec fonction tare et piles incluses.",
      full_description: "Balance de cuisine jusqu'à 10 kg, avec fonction tare et piles incluses.",
    },
  },
  "rynex-twinmarkers-168-stuks": {
    en: {
      name: "Twin Markers, 168 Pack",
      short_description:
        "168 double-ended alcohol markers for drawing, illustration and hand lettering.",
      full_description:
        "168 double-ended alcohol markers for drawing, illustration and hand lettering.",
    },
    de: {
      name: "Twinmarker, 168 Stück",
      short_description:
        "168 doppelseitige Alkoholmarker zum Zeichnen, Illustrieren und Handlettering.",
      full_description:
        "168 doppelseitige Alkoholmarker zum Zeichnen, Illustrieren und Handlettering.",
    },
    fr: {
      name: "Marqueurs double pointe, lot de 168",
      short_description:
        "168 marqueurs à alcool double pointe pour le dessin, l'illustration et le lettrage.",
      full_description:
        "168 marqueurs à alcool double pointe pour le dessin, l'illustration et le lettrage.",
    },
  },
  "rynex-twinmarkers-80-stuks": {
    en: {
      name: "Twin Markers, 80 Pack",
      short_description:
        "80 double-ended alcohol markers for drawing, illustration and hand lettering.",
      full_description:
        "80 double-ended alcohol markers for drawing, illustration and hand lettering.",
    },
    de: {
      name: "Twinmarker, 80 Stück",
      short_description:
        "80 doppelseitige Alkoholmarker zum Zeichnen, Illustrieren und Handlettering.",
      full_description:
        "80 doppelseitige Alkoholmarker zum Zeichnen, Illustrieren und Handlettering.",
    },
    fr: {
      name: "Marqueurs double pointe, lot de 80",
      short_description:
        "80 marqueurs à alcool double pointe pour le dessin, l'illustration et le lettrage.",
      full_description:
        "80 marqueurs à alcool double pointe pour le dessin, l'illustration et le lettrage.",
    },
  },
};

/**
 * Attaches the right translations to a bundled category or brand.
 *
 * The category and brand pages read the generated catalogue directly rather
 * than going through the server's row mapping, so they need the same
 * translations attached before `localize()` can find them.
 */
export function withCategoryTranslations<T extends { slug: string }>(
  category: T,
): T & { translations: Translations } {
  return { ...category, translations: CATALOGUE_CATEGORY_TRANSLATIONS[category.slug] ?? null };
}

export function withBrandTranslations<T extends { slug: string }>(
  brand: T,
): T & { translations: Translations } {
  return { ...brand, translations: CATALOGUE_BRAND_TRANSLATIONS[brand.slug] ?? null };
}
